# Generated by Django 2.2.7 on 2019-11-07 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.URLField()),
                ('short', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.IntegerField()),
                ('visits', models.DateTimeField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='shortener.Link')),
            ],
        ),
    ]
