# Generated by Django 2.2.7 on 2019-11-08 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='visits',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
