# Generated by Django 2.2.7 on 2019-11-08 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20191108_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.DateTimeField(default=datetime.datetime.now)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='shortener.Link')),
            ],
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
